name: transfer issue1
on:
  issues:
    types:
      - labeled
jobs:

  pass-secret-to-action:
    runs-on: ubuntu-latest
    steps:
      - name: Pass the received secret to an action
        uses: lando/transfer-issue-action@v2.0.3
        with: 
          token: ${{ secrets.ACCESSTOKEN }} 
          router: stale:ex1
