name: transfer issue
on:
  issues:
    types:
      - labeled
jobs:

  pass-secret-to-action:
    runs-on: ubuntu-latest
    steps:
      - name: Moving issue to Elsmart repo
        uses: lando/transfer-issue-action@v2.0.3
        with: 
          token: ${{ secrets.CLASSICACCESSTOKEN }} 
          router: Elsmart:Elsmart-Inbox
      
      - name: Moving issue to NETBAS repo
        uses: lando/transfer-issue-action@v2.0.3
        with: 
          token: ${{ secrets.CLASSICACCESSTOKEN }} 
          router: NETBAS:NETBAS-inbox
